apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.server.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.servicePort }}
      targetPort: server-port
